name: sisu-kodo
system_database_url: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${SYS_DB_NAME}
system_database_schema_name: dbos
runtimeConfig:
  admin_port: ${ADMIN_PORT}
  queues:
    compileQ:
      concurrency: 10
      priority_enabled: true
    sandboxQ:
      concurrency: 20
      priority_enabled: true
    controlQ:
      concurrency: 5
      priority_enabled: true
    intentQ:
      concurrency: 10
