name: sisu-kodo
system_database_url: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${SYS_DB_NAME}
system_database_schema_name: dbos
runtimeConfig:
  admin_port: ${ADMIN_PORT}
queues:
  intentQ:
    concurrency: 10
